title: SoLoBlack
subtitle: 小码农的成长之路 
link: Homepage link
meta:
  description: Content of description meta tag
  keywords: !!seq
    - keyword1
    - keyword2
    - keyword3
  author: Content of author meta tag
master:
  name: SoLoBlack
  about: Coding,Learning
  email: thesoloblack@gmail.com
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: SoLoBlack
  beginYear: 2014
  endYear: 2014
theme: default
codetheme: night
